name: Deploy to VPS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4 

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0 
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT || 22 }} 
          script: |
            cd /home/${{ secrets.VPS_USERNAME }} 
            
            ./github-actions-rebuild.sh reverse-proxy
            
            echo "Rebuild script execution finished on VPS."